### ISSUE TITLE
Standup overwrote bitcoin.conf

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#32]
I was doing a demo of todays version (2019-11-19 ) on another machine which already had `brew cask bitcoin-core` on it, and a mainnet full node -tx index.

The Standup button overwrote over the bitcoin.conf, breaking my previous configuration, even though I told the app to be configured for testnet.

a) You shouldn't overwrite the mainnet bitcoin.conf if testnet is being added.

b) At minimum the user should be warned there is a bitcoin.conf, and if they want to continue mv the old version to a dated backup.

c) Ideally bitcoin.conf already exists it should be scanned to see if it has what Bitcoin Standup needs, and only set those additional parameters that Bitcoin Standup needs, and if they conflict, ask the user.

-- Christopher Allen

**Comment by ChristopherA** [comment]
In my defaulf configuration, there is a bitcoin.conf in the testnet3 dir with testnet config. Newer version of bitcoind support this.

**Comment by Fonta1n3** [comment]
I propose to use `~/StandUp/BitcoinCore/Data` as the default `datadir` for StandUp to avoid this issue upon initial set up for now. Whenever the user launches Bitcoin Core via the StandUp console it will append the `datadir` argument e.g. `bitcoin-qt -datadir=~/StandUp/BitcoinCore/Data`. This way we completely avoid what you experienced and StandUp can operate completely quarantined from any existing Bitcoin software and configurations by default. 

The user may also manually choose a `datadir` in settings ( I am working on this now), when they do so I will make sure it checks if a bitcoin.conf file exists there already and then parse it, appending only the needed settings rather then overwriting the entire conf.

I didn't realize testnet3 had its own conf altogether, I have been taking the sectioned approach:

```
# Options only for mainnet
[main]

# Options only for testnet
[test]

# Options only for regtest
[regtest]
```

**Comment by ChristopherA** [comment]
I'm still not quite comfortable with moving the datafiles to a new directory. What if they open bitcoin-core directly — it will open the bitcoin.conf from the platform default directory? I also know that I personally have a number of scripts, both utility and in my bitcoin course, that use either that path directly or a shell variable that will give platform specific path. I worry about people accidentally having two different full nodes on a single machine.

I know that this makes us be more careful, requiring us to identify, backing up, and parse bitcoin.conf. I'm ok with temporary doing a different datadir in the short-term may be required, but I think ideally we should use the platform path.

**Comment by Fonta1n3** [comment]
That makes complete sense. Will revert back. The logic for working with the bitcoin.conf is append only now (if one exists)

**Comment by ChristopherA** [comment]
My proposal for testing this is to brew cask install bitcoin-core, start the app to start a default download, and make sure that the standup script doesn’t overwrite

**Comment by Fonta1n3** [comment]
This [PR](https://github.com/BlockchainCommons/Bitcoin-Standup/pull/34) fixes this and seems to be working as expected, please let me know if any issues. 

StandUp now syncs with the existing conf (if there is one) and updates the "Settings" view controller options based on what already exists. When StandingUp the exisiting conf will not be overwritten.

It also allows the user to update the conf with precision, it parses whether or not the setting to be updated is global or in a network section eg `[test]`, if it is in a network section it will not make the change unless the user switches to the desired network first.

If the user does not set a custom `datadir` then StandUp will automatically either parse the mainnet `~/Library/Application Support/Bitcoin/bitcoin.conf or the `.../Bitcoin/testnet3/bitcoin.conf` depending on what network they select in "Settings".

Also worth noting I ran into an error because I had specified a `datadir` in the bitcoin.conf but StandUp launches bitcoin core like so `sudo -u $(whoami) ~/StandUp/BitcoinCore/$PREFIX/bin/bitcoin-qt -datadir="$DATADIR" -chain=$CHAIN`, therefore you may get an error if you have `datadir`, `testnet` or `regtest` set in your conf. StandUp checks for this and will let you know what the issue is.
