### ISSUE TITLE
Storyboards and IB?

### ISSUE THREAD

**Issue by doffing81** [BlockchainCommons/Bitcoin-Standup#51]
In briefly surveying things, I have noticed that Storyboards and Interface Builder are used rather extensively, and I wonder if they are appropriate for an open source project? I’m not sure how debatable this is, but if such a consideration has not come to mind, it should perhaps at least come into question? While there are perhaps a few different things to consider, I’ll just leave this [Medium article](https://medium.com/remote-technologist/avoid-storyboards-and-interface-builder-cc3363de4782) as a good point of reference. I wouldn’t think this to be a small task, so I simply wonder if this is something that could warrant a new branch or draft pull request, where it could be chipped away at, or if it is even something to consider at all?

**Comment by Fonta1n3** [comment]
Hey Doffing, I will certainly check out the medium article and get back to you. Of course we want to optimize the project for open source and make it easy for others to get involved so are certainly open to suggestions. FYI the iOS official repo has been moved [here](https://github.com/BlockchainCommons/FullyNoded-2). We appreciate your contributions, please also check out the Contributor License Agreement form to be PGP signed [here](https://github.com/BlockchainCommons/FullyNoded-2/blob/master/CLA.md) with some instructions at the bottom. 

As far as making a PR to move away from using Storyboard, it would probably be a good idea to wait for the UI to mature a bit more otherwise you may be changing a component which gets removed altogether and wasting your time. The app is under *very* active development and there will probably be drastic changes. I will ping you about some of our high priorities asap :)

**Comment by doffing81** [comment]
Great, and thank you for the info/links. It makes sense to wait. Knowing that active development is happening, it seemed appropriate to simply raise the issue for awareness, and it also seemed like it might be a good fit for an active branch or PR, which I am looking to familiarize myself with.

**Comment by ChristopherA** [comment]
We have now split the repo, with the bnewly renamed “FullyNoded 2” iOS app at https://github.com/BlockchainCommons/FullyNoded-2

Can you repost your issue there and close this one?

We appreciate your thoughts & contributions!

— Christopher Allen
